#cloud-config
repo_update: true
repo_upgrade: all

runcmd:
- [wget, "https://s3.amazonaws.com/cloudhsmv2-software/CloudHsmClient/Amzn2023/cloudhsm-cli-latest.amzn2023.aarch64.rpm"]
- [sudo, yum, install, "./cloudhsm-cli-latest.amzn2023.aarch64.rpm", -y]